### ISSUE TITLE
On the preferences section, email is solicited and required even after not opting-in

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/michigan-benefits#2]
After opting only for text message follow ups, or opting out of all follow ups on this step:
`/steps/preferences-reminders`
![image](https://cloud.githubusercontent.com/assets/2983464/25018311/c77f4610-203b-11e7-9997-02c457eea898.png)

The user is always asked to provide their email address on the following page. That email is a required field:
![image](https://cloud.githubusercontent.com/assets/2983464/25018364/f2d9d690-203b-11e7-927e-9ec47211a574.png)

Two things should happen:
1) If neither "text message" or "email" are selected, then we should skip:
`steps/preferences-reminders-confirmation`

2) If only "text message is selected", we should omit or hide the question asking for an email address.

**Comment by alanjosephwilliams** [comment]
@eahanson if you do have a few minutes, this change would probably be the highest value among those identified so far.

**Comment by eahanson** [comment]
Fixed in 64c3a226aa94e0e9963d4c87c01e5013f89110d7 .
