### ISSUE TITLE
Two different kinds of back is a little confusing

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/michigan-benefits#3]
When I'm in the app, I hit back using the blue arrow at the top, which took me to the previous page in the form. Then I hit the back arrow on my browser, it took me _forward_ in the form, which was confusing.

**Comment by alanjosephwilliams** [comment]
That _is_ confusing!  @bengolder do you recall which page you were on (or which page you were taken to) when you hit back in the browser, but went _forward_ in the form?

**Comment by bengolder** [comment]
@alanjosephwilliams sorry, I'm having trouble finding the link to the site. You should be able to reproduce by:
1. start a new application, go several pages in.
2. hit the blue "back" arrow in the app (this will take you to the previous form page)
3. hit the "back" arrow in the browser (this should take you forward)

**Comment by alanjosephwilliams** [comment]
Thanks @bengolder!

**Comment by adarsh** [comment]
@alanjosephwilliams this feels pretty stale. Closing for now, please re-open if I'm being hasty.
