### ISSUE TITLE
CfA Office User Testing

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/michigan-benefits#4]
Some thoughts:
- TANF is missing under temp assistance
- didn't flag that my zip code was outside of Michigan (but did flag incorrect email and phone)
- when I apply as a single person with no dependents, the language doesn't adjust (i.e. tell us about each person in your household)
- when I come back to a saved app, I have to click through all the pages again. It's annoying
- thought it would tell me what I was eligible for and how much $$ I may get

**Comment by adarsh** [comment]
@alanjosephwilliams this feels pretty stale. Closing for now, please re-open if I'm being hasty.
