### ISSUE TITLE
Audit keyboards triggered on input selection, and update to ensure best selection

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/michigan-benefits#6]
There are a number of inputs that currently trigger the default keyboard, despite being primarily numeric input. Let's conduct an audit of all keyboards trigger, and optimize each input accordingly.

**Comment by eahanson** [comment]
I seem to remember that on GetCalFresh, we learned that some special keyboards had usability issues on older Android operating systems. We may want to test any changes on older phones.

**Comment by adarsh** [comment]
@alanjosephwilliams this feels pretty stale. Closing for now, please re-open if I'm being hasty.
