### ISSUE TITLE
Styleguide code link from DESIGN-README leads to 404 page

### ISSUE THREAD

**Issue by ericbenwa** [codeforamerica/michigan-benefits#782]
The link for text 'Styleguide code' found here 
https://github.com/codeforamerica/michigan-benefits/blob/master/DESIGN-README.md

leads to this link which is a 404
https://github.com/codeforamerica/gcf-backend/tree/master/app/views/styleguides

**Comment by hartsick** [comment]
Hey there—thanks for reporting! Looks like our styleguide code is now in a private repository. I'll see what we can do to make it public, and will update the readme until we get that sorted out.
